name = "lms-telegram-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

# D1 Database - замените на ваш реальный database_id
[[d1_databases]]
binding = "DB"
database_name = "lms-database"
database_id = "YOUR_DATABASE_ID_HERE"

# Переменные окружения - только несекретные значения
[vars]
ADMIN_LOGIN = "admin"
# Остальные секреты будут установлены через wrangler secret 